defaults: ./grpo-deepseek-v3-32n8g.yaml
checkpointing:
  checkpoint_dir: results/grpo-deepseek-v3-32n4g
policy:
  sequence_packing:
    enabled: false
  megatron_cfg:
    pipeline_model_parallel_size: 8
    expert_model_parallel_size: 16
    num_layers_in_first_pipeline_stage: 7
    num_layers_in_last_pipeline_stage: 6
  generation:
    vllm_cfg:
      tensor_parallel_size: 16
logger:
  log_dir: logs/grpo-deepseek-v3-32n4g
  wandb:
    name: grpo-deepseek-v3-32n4g
cluster:
  gpus_per_node: 4
  num_nodes: 32
