defaults: ./grpo-qwen3-235b-32n8g-async-1off.yaml
checkpointing:
  checkpoint_dir: results/grpo-qwen3-235b-32n4g-async-1off
policy:
  megatron_cfg:
    pipeline_model_parallel_size: 4
    num_layers_in_first_pipeline_stage: 23
    num_layers_in_last_pipeline_stage: 23
  generation:
    colocated:
      resources:
        gpus_per_node: 4
    vllm_cfg:
      tensor_parallel_size: 8
logger:
  log_dir: logs/grpo-qwen3-235b-32n4g-async-1off
  wandb:
    name: grpo-qwen3-235b-32n4g-async-1off
cluster:
  gpus_per_node: 4
  num_nodes: 32
