defaults: ./grpo-deepseek-v3-64n8g-async-1off.yaml
checkpointing:
  checkpoint_dir: results/grpo-deepseek-v3-64n8g-fp8-async-1off
policy:
  megatron_cfg:
    fp8_cfg:
      enabled: true
      fp8: "e4m3"
      fp8_recipe: "blockwise"
      fp8_param: false
    moe_router_dtype: fp32
    env_vars:
      NVTE_FP8_BLOCK_SCALING_FP32_SCALES: "1"
  generation:
    vllm_cfg:
      tensor_parallel_size: 16
      precision: "fp8"
      use_deep_gemm: true
      quantization_ignored_layer_kws: [
        a_proj,
        b_proj
      ]
    vllm_kwargs:
      max_num_seqs: 32
logger:
  log_dir: logs/grpo-deepseek-v3-64n8g-fp8-async-1off
  wandb:
    name: grpo-deepseek-v3-64n8g-fp8-async-1off
