defaults: ./grpo-llama3.1-8b-instruct-2n8g-async-1off.yaml
checkpointing:
  checkpoint_dir: results/grpo-llama3.1-8b-instruct-2n8g-fp8-async-1off
policy:
  megatron_cfg:
    fp8_cfg:
      enabled: true
      fp8: "e4m3"
      fp8_recipe: "blockwise"
      fp8_param: false
    env_vars:
      NVTE_FP8_BLOCK_SCALING_FP32_SCALES: "1"
  generation:
    vllm_cfg:
      precision: "fp8"
      use_deep_gemm: true
logger:
  log_dir: logs/grpo-llama3.1-8b-instruct-2n8g-fp8-async-1off
  wandb:
    name: grpo-llama3.1-8b-instruct-2n8g-fp8-async-1off